.gitignore, Makefile, src/asyncProfiler.cpp, src/asyncProfiler.h, src/vmEntry.cpp
* Ignoring `nbproject`
* Support for darwin compilation
* Using `dlsym()` to load `AsyncGetCallTrace` from JVM
* Fixed timer parameters
* Processing return codes of system calls
* Using `snprintf()` instead of `sprintf()`
* Counting distinct frame errors
=> Minor fixes from testing on MacOS

src/asyncProfiler.cpp, src/asyncProfiler.h, src/vmEntry.cpp
Now you can dynamically attach `async-profiler` and pass it the following options:
1. `frameBufferSize:<size>` to set the size of the frame buffer
2. `start` to start profiling
3. `stop` to stop profiling
4. `dumpRawTraces:<file>` to dump collected stack traces into `<file>` in `lightweight-java-profiler` format
Then you can process the stack traces and build flame graphs:
```sh
echo "Collapsing stacks into ${STACKS}..."
cat $RAW | ${FLAMEGRAPH_DIR}/stackcollapse-ljp.awk >$STACKS
echo "Collapsing recursion into ${NON_RECURSIVE}..."
cat $STACKS | sort | ${FLAMEGRAPH_DIR}/stackcollapse-recursive.pl >$NON_RECURSIVE
echo "Building SVG into ${SVG}..."
cat $NON_RECURSIVE | ${FLAMEGRAPH_DIR}/flamegraph.pl >$SVG
```
Changes:
* `Agent_OnAttach` resolves `AsyncGetCallTrace` each time to support …
=> Support for flame graph building

src/vmEntry.cpp
A user can pass `freq:<freq>,start` options to the agent to start profiling with custom frequency.
=> Support for custom profiling frequency through agent option

src/asyncProfiler.cpp, src/asyncProfiler.h
On `Profiler::start()` we set `SIGPROF` signal handler and start the timer.
On `Profiler::stop()` we just stop the timer.
Otherwise, resetting `SIGPROF` signal handler on `Profiler::stop()` under frequent `start()`/`stop()` calls leads to early termination of the application due to unprocessed signal.
=> Keep sigprofHandler always set

src/codeCache.cpp
Replace spaces with underscores in symbol names instead of terminating on space.
=> Escape symbol names instead of stripping

README.md, src/codeCache.cpp, src/codeCache.h, src/profiler.cpp, src/profiler.h, src/symbols.cpp
- `dumpRawTraces` now prints stack traces in the FlameGraph format, so the intermediate step of running `stackcollapse-ljp` is no longer needed;
- Java classes are printed in the slashed format (e.g. java/lang/Thread), and `_[k]` is appended to the kernel symbols to match `--colors=java` scheme of the FlameGraph script.
=> Dump traces in FlameGraph format

.travis.yml
This introduces a .travis.yml file that configures a Travis CI
build to run on Ubuntu Trusty (14.04), install the JDK, and build
the project. The next step would be adding automatic tests.
You can see over here what the result looks like (enabled for
my fork of the repo): https://travis-ci.org/goldshtn/async-profiler/builds
@apangin You would need (as the repo owner) to log in on
https://travis-ci.org, authorize Travis to access your GitHub
repositories, and check the checkbox next to the async-profiler
repository so that we get an automatic build. Then we could
add a build badge, configure pull requests to require the build
to pass, and so on. If you'd like I can configure this for you,
but you would need to give me admin access to the repo.
Resolves #20.
=> Basic TravisCI support

.gitignore, .travis.yml, Makefile, README.md, profiler.sh, test/Target.java, test/smoke-test.sh
The smoke test runs the Java target application, attaches the profiler,
waits for 5 seconds, stops the profiler and dumps the results to a
file, and then parses the file looking for patterns that we know
must appear. This is a very basic smoke test that will only make sure
we haven't broken anything completely obvious.
The Makefile and Travis configuration are also updated to run the test.
Resolves #21.
=> Basic smoke test support

src/codeCache.cpp, src/codeCache.h, src/profiler.cpp, src/profiler.h, src/symbols.cpp, src/symbols.h
If shared library misses .strtab section, look for debug symbols in the external sources:
1. /usr/lib/debug/.build-id/ab/cdef1234.debug, where abcdef1234 - is ID obtained from `.note.gnu.build-id` section;
2. /usr/lib/debug/path/to/lib.so
3. /usr/lib/debug/path/to/lib.so.debug
4. /path/to/lib.so.debug
Note: to keep things simple we do not parse .gnu_debuglink contents, but rather search through a list of common locations.
=> Parse external debuginfo

Makefile, src/codeCache.cpp, src/profiler.cpp, src/profiler.h, src/vmEntry.cpp
Change profiler state between IDLE/RUNNING/TERMINATED  under state_lock.
This will delay VM termination until all pending profiler output is completed.
=> #25: Guard state transitions by a mutex

src/perfEvent.cpp, src/spinLock.h, src/symbols.cpp
Resolves #28
Fixed compiler errors encountered on older systems:
- '__builtin_ia32_pause' was not declared in this scope
- 'SYS_perf_event_open' was not declared in this scope
- aggregate 'f_owner_ex ex' has incomplete type and cannot be defined
- 'F_OWNER_TID' was not declared in this scope
- 'F_SETOWN_EX' was not declared in this scope
- 'NT_GNU_BUILD_ID' was not declared in this scope
Tested on Linux 2.6.39, gcc 4.1.2, JDK 6u26
=> #28: Support older gcc and Linux headers

src/jattach.c
Currently if one has problems with permissions, jattach will print
`Connected to remote JVM` to stdout and silently exits due to unhandled `SIGPIPE` signal.
Before patch:
```
./profiler.sh -p ... -a start 
echo $?
141
```
After patch:
```
./profiler.sh -p ... -a start
Error writing to socket: Broken pipe
echo $?
1
```
=> Ignore SIGPIPE during socket operations to avoid silent exits

src/codeCache.cpp, src/codeCache.h, src/perfEvent.cpp, src/profiler.cpp, src/profiler.h, src/spinLock.h, src/symbols.cpp, src/symbols.h, src/vmEntry.h
Call traces are now stored as an array of `ASGCT_CallFrame` (instead of an array of `jmethodID`).
`bci` field is used to distringuish Java methods from native functions. The special value -2 means that jmethodID should be treated as a string holding the native function name.
Related changes:
- StringTable is completely removed; all function names are strdup'ed.
- CodeCache is split into Java CodeCache and NativeCodeCache: the former holds `jmethodID` while the latter holds `const char*`.
- JITted methods and VM generated stubs are now in two separate CodeCaches.
- CodeCache is updated under lock; when it grows, the previously allocated memory is reclaimed.
Linux/ARM builds do not crash anymore during profile dumping.
=> Resolves #32: Revise usage of jmethodID to encode strings

README.md, profiler.sh, src/arguments.cpp, src/arguments.h, src/javaApi.cpp, src/profiler.cpp, src/profiler.h, src/vmEntry.cpp, test/smoke-test.sh
Here is a number of improvements both to parsing of Agent arguments and to profiler.sh command-line interface.
1. Moved arguments processing to the separate `arguments.cpp` file.
2. Removed the timeout check from the agent code (it did not work anyway). Now it is responsibility of the wrapper script to stop the profiling after the specified period of time.
3. Added `-d` (duration) option to profiler.sh. It allows to execute start-wait-stop sequence with just one command.
4. Allowed to dump any combination of profiling data (summary / flat profile / call stacks / flamegraph) also with just one command.
5. Filename option now works not only for the flamegraph format, but for any combination of output formats above.
6. Added --status option to print whether profiler is active and for how …
=> Better argument processing. Resolves #15, #19, #27.

profiler.sh, src/jattach.c, src/profiler.cpp, src/profiler.h, src/symbols_macos.cpp, src/vmEntry.cpp, src/vmStructs.cpp, src/vmStructs.h, test/AllocatingTarget.java, test/Target.java, test/alloc-smoke-test.sh
Allocation profiler support is added, `profiler.sh` is fixed, `VMStructs::init` rewritten to be used both by mac os x and linux builds, new test added.
Some comments about implementation:
1) `VMStructs::init` rewrite wasn't necessary, but now the code is shared between OSes
2) `realpath` in jattach can be avoided by using some bash/perl scripting in `profiler.sh`
3) Loaded jvm is found via private API (moreover, hidden in current release), I'd appreciate if someone will test it on any version different from 10.12.5
4) Tested on both linux (CentOS 3.10.0) and mac os x (10.12.5)
=> Mac os x support

README.md, src/allocTracer.cpp, src/arguments.cpp, src/arguments.h, src/frameName.cpp, src/frameName.h, src/javaApi.cpp, src/perfEvent.cpp, src/perfEvents_linux.cpp, src/perfEvents_macos.cpp, src/profiler.cpp, src/profiler.h, src/vmEntry.h, test/alloc-smoke-test.sh
- Collect counter values in addition to number of samples.
- Added option to output either counter total value or number of samples in collapsed format. In particular, heap profiles can now display either object count or their total size.
- Distinguish between allocations in new TLAB vs. allocations outside TLAB. They are displayed in different color in flame graph.
- Pretty class names in allocation profile, e.g. `java.lang.Integer[]` instead of `[Ljava/lang/Integer;`
Resolves #46
=> Alloc details

src/vmEntry.cpp
Attempting to use async-profiler on Java code that has been launched by C++ code which dynamically loads libjvm.so and then starts embedded JVM via [JNI_CreateJavaVM()](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html) results in:
> Could not find AsyncGetCallTrace function
That is because current attempt to load this function is only via RTLD_DEFAULT. In case of failure, we can try loading AsyncGetCallTrace from libjvm.so explicitly to handle this edge case.
=> Load AsyncGetCallTrace from libjvm.so

README.md, profiler.sh, src/arguments.cpp, src/arguments.h, src/frameName.cpp, src/frameName.h, src/javaApi.cpp, src/perfEvents.h, src/perfEvents_linux.cpp, src/perfEvents_macos.cpp, src/profiler.cpp, src/profiler.h, src/vmEntry.h, src/vmStructs.cpp, src/vmStructs.h, test/AllocatingTarget.java, test/Target.java, test/alloc-smoke-test.sh
Complement stack traces with a frame denoting a thread.
Use Java thread names where possible. Otherwise fall back to native thread ID.
=> #65: Add '-t' option to split profile by threads

profiler.sh, src/arguments.cpp, src/arguments.h, src/javaApi.cpp, src/profiler.cpp, src/profiler.h, src/vmEntry.cpp, src/vmEntry.h
- Profiler can start immediately after JVM bootstrap, if specified with `-agentpath` option
- Dump collected data if JVM terminates prematurely
- profiler.sh script exits as soon as target JVM dies
=> #49: Ability to start profiler together with JVM and dump profile on exit

CHANGELOG.md, README.md, demo/SwingSet2.svg, docs/cddl1.txt, profiler.sh, src/arguments.cpp, src/arguments.h, src/flameGraph.cpp, src/flameGraph.h, src/profiler.cpp, src/profiler.h
- New output format: `-o svg`
- Automatically choose output format depending on file extension
- Removed references to `flamegraph.pl`
=> Built-in generator of Flame Graphs in SVG format

src/arch.h
Fixes compile on alpine linux where PAGE_SIZE is already defined in /usr/include/bits/limits.h (and included via /usr/include/limits.h)
=> Check if PAGE_SIZE is already defined.

src/lockTracer.cpp, src/lockTracer.h
Substitute `Unsafe.park()` native entry to measure `park()` time of ReentrantLocks.
=> #90: Profile ReentrantLock contention

README.md, profiler.sh, src/arguments.cpp, src/arguments.h, src/profiler.cpp, src/profiler.h
We have experimented with reduced java stack and observed less CPU overhead. This could be a useful option for others too.
Added a new option "-j jstackdepth" to control the java stack depth that AsyncGetCallTrace fetches.
Conditions are added to make sure that the total stack frames (native+java) are not exceeding MAX_STACK_FRAMES.
This option is applied only when event type is "cpu"
=> Option to limit java stack depth to reduce CPU overhead

Makefile, test/alloc-smoke-test.sh, test/smoke-test.sh
Hi,
I found the issue:
```
$ make test
test/smoke-test.sh
+ '[' -z '' ']'
+ echo 'JAVA_HOME is not set'
JAVA_HOME is not set
```
when dynamically calculated `JAVA_HOME` variable is not passed to test scripts, like `smoke-test.sh` and `alloc-smoke-test.sh`.
This PR adds export of `JAVA_HOME` variable to the environment of subsequently executed commands.
=> Pass JAVA_HOME variable to test scripts

README.md
This commit adds a brief yet not-completely-obvious note about how to get symbols into the
'icedtea' OpenJDK package on Gentoo Linux. The approach worked for me when I
tried async-profiler last night and (of course) initially had no symbols;  after rebuilding icedtea
with "nostrip" I got perfectly good profiles.
=> README: add note about how to build icedtea with symbols on Gentoo

profiler.sh
If we parameters as described in documentation, we don't get the expected output file.
Using an absolute path seems to be required to behave as expected.
=> Use absolute path for output file

src/frameName.cpp, test/alloc-smoke-test.sh
In our inner fork we use '[' and ']' to understand that thread dump has named threads(if first frame starts with '[' and ends with ']' and it isn't  `[unknown]` it should be thread name)
And when users decide to use upstream version they have funny bugs, like this: https://youtrack.jetbrains.com/issue/IDEA-200453
I also add thread id information for JVM threads do distinguish different threads with same name and to match profiler info to other collected thread related data, if any.
=> fix thread names format

src/allocTracer.cpp, src/allocTracer.h, src/arguments.h, src/engine.cpp, src/engine.h, src/flightRecorder.cpp, src/lockTracer.h, src/os.h, src/os_linux.cpp, src/os_macos.cpp, src/perfEvents.h, src/perfEvents_linux.cpp, src/perfEvents_macos.cpp, src/profiler.cpp, src/profiler.h, src/wallClock.cpp, src/wallClock.h
`-e wall` option that enables fixed-interval timer and samples all threads by sending signals to them
=> Wall-clock profiling

README.md
Document the placeholders for the PID and the timestamp
in a filename.
See https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/arguments.cpp#L189-L190
=> Document the placeholders in the file name

README.md
When attempting to run the async-profiler in a Docker context, I encountered issues with the syntax for `seccomp` as specified in the README.
From https://docs.docker.com/engine/reference/run/:
> use `--security-opt seccomp=unconfined` when adding capabilities
=> Fix syntax for Docker seccomp, and add note about --cap-add

Makefile
It could not build by Java 13 due to hard-coding and out-of-support.
before
<details>
```
$ PROFILER_VERSION=13 JATTACH_VERSION=13 make -e
/jdk-13.0.1/bin/javac -source 6 -target 6 -d build/classes src/java/one/profiler/Events.java src/java/one/profiler/AsyncProfiler.java src/java/one/profiler/AsyncProfilerMXBean.java src/java/one/profiler/Counter.java
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
make: *** [build/async-profiler.jar] Error 2
```
</details>
after
<details>
```
$ PROFILER_VERSION=13 JATTACH_VERSION=13 make -e
/jdk-13.0.1/bin/javac -source 13 -target 13 -d build/classes src/java/one/profiler/Events.java …
```
=> Make release version of javac specifiable

src/codeCache.cpp, src/codeCache.h
Check that code blob is not removed to avoid returning NULL
when another code blob loaded at the similar address range
that was used by removed one
Contributed by @semoro
=> Ensure code blob exists properly

profiler.sh
- use POSIX sh instead of bash (not available on most embedded linux, alpine, etc)
- replace some bash-isms by sh alternatives
- some shellcheck warnings
- replace usage of readlink by cd & pwd (not everybody has coreutils installed)
=>  profiler.sh: work on minimal systems

src/javaApi.cpp
Otherwise the first missing native declaration in the
Java class will abort registration. This hinders the ability
to add natives to the API without breaking "copy/paste" client
implementations.
=> Register natives one-by-one to support partial Java API implementations

README.md, profiler.sh
I found the `jps` parameter helpful, so I extended it to use the application name as it would appear in the `jps` list.
=> Specify JVM process by 'jps' application name

README.md
I ran into an odd case where I tried to alloc profile a running process, the debug symbols were missing, I installed the debug symbols, the profiling continued to fail. This was because the JDK was upgraded when I installed the debug symbols. I added to the troubleshooting section to spare others the investigative work.
I broke the debug symbol information into a separate subsection for anchoring/linking. I also added note in the CPU section that the debug symbols are needed if one wanted resolve frames within libjvm.so. "Wall-clock profiling" section was promoted since it is not a subsection of "ALLOCATION profiling".
=> Clean up debug symbols instructions and troubleshooting

profiler.sh, src/perfEvents_linux.cpp, src/profiler.cpp
New events to be selected in `-e` option:
- Raw PMU event, e.g. `r4d2` selects `MEM_LOAD_L3_HIT_RETIRED.XSNP_HITM` event, which corresponds to event 0xd2, umask 0x4
- PMU event descriptor, e.g. `cpu/event=0xd2,umask=4/`. The same syntax can be used for uncore and vendor-specific events, e.g. `amd_l3/event=0x01,umask=0x80/`
- Symbolic name of a dynamic PMU event, e.g. `cpu/topdown-fetch-bubbles/`
- kprobe/kretprobe, e.g. `kprobe:do_sys_open`, `kretprobe:do_sys_open`
- uprobe/uretprobe, e.g. `uprobe:/usr/lib64/libc-2.17.so+0x114790`
=> Raw PMU events; kprobes & uprobes

src/itimer.cpp
This fixes the build on macOS:
Before:
```
src/itimer.cpp:57:34: error: non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
struct itimerval tv = {{sec, usec}, {sec, usec}};
^~~~
src/itimer.cpp:57:34: note: insert an explicit cast to silence this issue
struct itimerval tv = {{sec, usec}, {sec, usec}};
^~~~
static_cast<__darwin_suseconds_t>( )
src/itimer.cpp:57:47: error: non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
struct itimerval tv = {{sec, usec}, {sec, usec}};
^~~~
src/itimer.cpp:57:47: note: insert an explicit cast to silence this issue
struct itimerval tv = {{sec, usec}, {sec, usec}};
^~~~ …
```
=> Use time types instead of long.

src/vmEntry.cpp
An updated version of https://github.com/jvm-profiling-tools/async-profiler/pull/456
We not only report JBR as hotspot, but also vanilla DCEVM, that being a fork of OpenJDK is definitely a hotspot.
=>  Recognise `DCEVM` as Hotspot

src/profiler.cpp
This amends async-profiler to handle OpenJDK C++ interpreter frames correctly, which resolves #472. This relies on OpenJDK supporting AGCT in C++ Interpreter: https://github.com/openjdk/jdk/pull/5848.
I think we can just terminate the C stack walk on encountering the C++ Interpreter frame, and leave the rest to AGCT. There is no need to handle the case when AGCT is not supported for C++ Interpreter (which would allegedly lose stack frames here without AGCT covering for us), because the unsupporting VM would just crash when trying to use AGCT. 
Additional testing:
=> Handle OpenJDK C++ Interpreter

src/converter/FlameGraph.java
I encountered it while converting collapsed files generated from a NodeJS perf. They include frames named `RegExp:` followed by the regular expression itself, which may contain backslashes. Expressions ending in `\` cause a syntax error because it escapes the closing quote.
This can be demonstrated with the following collapsed file:
```
blabla\ 1
blabla\\ 2
```
on master, the generated HTML fails to display (and Chrome complains about JS syntax error in the console).
On this branch, the graph is displayed correctly.
=> Escape backslashes in flamegraph frame names

src/symbols_linux.cpp
fclose() on an fdopen()ed file closes the underlying file descriptor.
Tested with this program:
```
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>
int main(void) {
int fd = open("/dev/null", O_RDONLY);
FILE *fp = fdopen(fd, "r");
fclose(fp);
close(fd);
}
```
stracing it results in:
```
openat(AT_FDCWD, "/dev/null", O_RDONLY) = 3
fcntl(3, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
brk(NULL)                               = 0x562a0bb5d000
brk(0x562a0bb7e000)                     = 0x562a0bb7e000
close(3)                                = 0
close(3)                                = -1 EBADF (Bad file descriptor)
```
Also from `fdopen(3)`: `The file descriptor is not dup'ed, and will be closed when the stream …
=> Remove double close() call

src/arguments.cpp
When using `profiler.sh` this probably can't happen, but for others writing other frontends, this can catch sad errors like typos in passed arguments, which are currently ignored :( Also, it might catch errors in existing frontends, who knows.
It would be nicer if the returned error included the argument name, but I see that the `Error` class expects a long-living `char *` pointer, and does no memory management on its own, so I can't pass a stack buffer (which is deallocated by the point the string is used) or a heap buffer (which will be leaked). Additionally, the `Log` object is not yet initialized, so I can't use it either.
A static string is still better than nothing, hence I'm proposing this PR as is.
~~I can maybe replace `} else {` with `#define DEFAULT` so it looks nicer?~~ done
=> Fail arguments parsing upon unknown argument

src/symbols_linux.cpp
Hi Andrei,
unfortunately the 'Patch Global Offset Table to hook libc functions' change broke the PPC64le port. The symbol is located in .plt on PPC64le. The fix is simple, and should not brake anything else. I did it together with my colleague Johannes (@parttimenerd) who will continue to help maintaining the port.
=> Look in plt sections for the global offset table too

src/arguments.cpp, src/arguments.h, src/javaApi.cpp, src/log.cpp, src/log.h, src/vmEntry.cpp
It allows to set the minimal log level to output. This is particularely
helpful if you're using async-profiler in production and where you don't
want to clubber your output with not always relevant log information.
=> Add loglevel argument

src/converter/Main.java, src/converter/jfr2pprof.java, src/converter/one/proto/Proto.java
Relates to https://github.com/jvm-profiling-tools/async-profiler/issues/343 and probably https://github.com/jvm-profiling-tools/async-profiler/issues/134
Assists by @dalehamel @bmansoob
This add a pprof converter.
Only CPU stats are carried over onto a minimal set of fields from the pprof proto definition.
We noticed flame graphs converted directly and those created via this new pprof and the Golang pprof tool contain slightly different percentages, which may be due to rounding errors along the way.
=> Add pprof converter

src/flightRecorder.cpp
When fetching info of a native method we try to get its library name by calling `Profiler::instance()->getLibraryName(name)`. However, to fetch this information we perform this cast: `(NativeFunc*)(name - sizeof(NativeFunc))` at `NativeFunc::from`. At the same time, at `Lookup::resolveMethod` we create a mock native frame for methods with a missing method id and assign them the name 'unknown'. For these methods the described cast can never succeed, it also leads to runtime errors if the profiler is compiled with Address Sanitizer. The same error happens with mock event frames with the 'no_Java_frame' name, which are created at `Profiler::recordSample`.
fixes #598
=> Remove library name fetching for unknown and error frames

profiler.sh, src/arguments.cpp, src/fdtransfer/fdtransfer.h, src/fdtransfer/fdtransferServer.cpp, src/fdtransferClient.h, src/fdtransferClient_linux.cpp, src/profiler.cpp
Closes: #634
This solves the problem described in #634.
I sanity-tested it by running `for p in $(pgrep java); do sudo ./profiler.sh -d 10 -e cpu -t -f xxx-$p.html -a -o flamegraph $p -i 50us --fdtransfer & ; done` on a system with 2 containerized Java apps; both are the same PID in their PID namespace. On `master`, it fails with `FdTransfer listen(): Address already in use`. On this branch, it passes.
=> Generate randomized fdtransfer path per async-profiler invocation

Makefile, README.md
Reintroduces the `JAVAC_RELEASE_VERSION` to allow developers to specify the Java bytecode version. The rational is that the minimally configurable byte code version goes from 7 to 8 in the JDK 20. This change allows building async-profiler with these JDKs too by using `make JAVAC_RELEASE_VERSION=8`, this his helpful when developing profiling APIs in the JDK.
This is related to #423, but just setting the bytecode version to 8 would be hard to justify as Azul supports Java 7 till 2027.
=> Allow to set Bytecode version for Java compile in makefile

README.md
Also remove a typo ",", it shouldn't be there.
=> Update README with C1/interpreted methods suffix info

README.md
Add [default values](https://github.com/jvm-profiling-tools/async-profiler/issues/360) in the `README.md`.
And according to the impl, the chunksize must be larger than 262,144 bytes. This also has to be mentioned in the document.
=> Chore: document chunksize and chunktime

Makefile, src/flameGraph.cpp
Tiny fix for the case that the current async-profiler folder contains `flame.html` or `tree.html` or files. The build script currently takes these files instead of the files from `src/res`, causing an error during the flame graph generation. This is problematic because `flame.html` is not an uncommon name for created flame graph files.
=> Fix build when the main folder contains `flame.html` or `tree.html` files

src/dictionary.cpp, src/safeAccess.h
Make codebase compile with `-std-c++2b`.
=> Compile with -std-c++2b without errors

src/arguments.h
When running `./profiler.sh` temporary output file is created for the agent.
All other actions write the result to this file both on success and on failure.
Before the fix:
```
./profiler.sh status jps
Profiler is not active
./profiler.sh check -e foo jps
[ERROR] PerfEvents are unsupported on macOS
./profiler.sh check -e cpu jps
```
After the fix:
```
./profiler.sh status jps
Profiler is not active
./profiler.sh check -e foo jps
[ERROR] PerfEvents are unsupported on macOS
./profiler.sh check -e cpu jps
OK
```
=> Action "check": print "OK" result to file

Makefile, src/arch.h, src/stackFrame_riscv64.cpp, src/symbols_linux.cpp
This PR adds the support for building and running on riscv64 platforms. I have built and tested it on HiFive Unmatched board running Ubuntu 22.04, and ran async-profiler with JMH -prof async and bleeding edge mainline JDK 20 build. The flamegraphs seem to make sense: it resolves C2 native code well, resolves compiled code well, etc.
I tested with `-Xint`, `-XX:TieredStopAtLevel=1` (C1), default (C2).
I still call this support "basic", because it is not tested beyound toy examples, and some features (like stub pops) are stubbed out.
=> Basic RISC-V support

src/converter/Arguments.java
Right now now [Arguments](https://github.com/async-profiler/async-profiler/blob/master/src/converter/Arguments.java) class is `package-private`, so is not possible to use `jfr2flame(JfrReader jfr, Arguments args)` programatically to create flamrgrpah (unless i copy the same class locally for non-module apps).  This PR is to make this class public to make it more API friendly.
=> Make converter Arguments class public

src/objectSampler.cpp
Hi Andrei
As discussed in [#873](https://github.com/async-profiler/async-profiler/issues/873).
Because [JEP 331](https://openjdk.org/jeps/331) doesn't return the actual pseudo-random `interval` in `JVM`, the `event._total_size` is the best we can use now.
I would appreciate it if you can help review this.
=> #873: the accuracy issue of ObjectSampler in --total mode

src/converter/jfr2pprof.java
- Do not use one.jfr.JfrReader#readAllEvents(java.lang.Class<E>) as it may trigger reading new chunk in multichunk jfrs, overwriting cp, producing wrong data(I observerd wrong class names). Note: it is still used in netflix code I did not touch.
- Use Location(method+line) as dedup key to fix line numbers
I've used this JFR file for testing, captured by Intellij IDEA Ultimate on Linux
[FastSlow_2024_01_16_180855.jfr.zip](https://github.com/async-profiler/async-profiler/files/13949433/FastSlow_2024_01_16_180855.jfr.zip)
=> fix(jfr2pprof): Fix multichunk jfr symbols and location's line numbers

src/converter/one/proto/Proto.java
Currently the `Proto` class determines whether to emit a continuing byte for the integer value `n` this way:
```java
while (n > 0x7f) {
```
The intention of the comparison is to check whether `n` has any bit set below the lowest 7 bits.  Unfortunately it does not work if `n` is negative, which causes the loop to be skipped entirely.  When that happens, the `jfr2pprof` produces a protobuf profile that is rejected by `pprof`.
This PR fixes the bug so that `Proto` encodes negative integer values correctly.
=> Fix Proto encoding of negative integers

src/flightRecorder.cpp
From [JVMTI-GetSystemProperties](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#GetSystemProperties) docs: Each of the elements should be freed with Deallocate.
It's easy to reproduce if there are many/big properties. 
Fast Reproducer:
```
public static void main(String[] args) {
for(;;) {}
}
```
`java -DTTTTTTT(very-very-very-long-string)=5 Main` I used 50k for fast reproducer.
`while true; do build/bin/asprof -e alloc -f profile.jfr -d 0.001 jps; done`
RSS increases very fast until OOM. NMT shows:
```
Details:
[0x00000001025bdf24] JvmtiEnv::GetSystemProperties(int*, char***)+0xf4
[0x00000001025815c0] jvmti_GetSystemProperties(_jvmtiEnv*, int*, char***)+0x108
[0x0000000100cd6d04] Recording::writeSystemProperties(Buffer*)+0x58
[0x0000000100cd5650] …
```
=> Fix memory leak of keys from jvmti->GetSystemProperties

demo/flamegraph.html, src/res/flame.html
* ctrl+f is already overridden
* On OS X the default way to search on page is command+f, would be nice to have it in flamegraphs as well
=> FlameGraph: search with Command+F key (⌘F) on mac

README.md, src/arguments.cpp, src/arguments.h, src/flightRecorder.cpp, src/main/main.cpp, src/os.h, src/os_linux.cpp, src/os_macos.cpp, src/profiler.cpp
Added `jfropts=mem` argument backed by `memfd_create` and supported on Linux 3.17+.
With this option, async-profiler does not dump events to a disk while profiling session is running. All events are flushed after the profiling session terminates.
As a side change, previously undocumented syntax `jfr=options` is no longer supported.
=> An option to accumulate JFR events in memory instead of flushing to a file

src/main/main.cpp
Hi, could I have a review of this PR. I would appreciate it.
Add --libpath option to specify the path of libasyncProfier.so in the container
https://github.com/async-profiler/async-profiler/issues/955
In async-profiler 2.9, there is an option --lib path in profiler.sh to specify the path of libasyncProfier.so in the container.
But in 3.0 and above, this option is missing. After [discussion](https://github.com/async-profiler/async-profiler/issues/955), I know that there is a plan is to make asprof automatically provide libasyncProfier.so to the process inside a container, but no timeline for this feature, adding --libpath is straightforward and acceptable.
The tests below ran in both container and non-container scenarios, all passed:
- If --libpath is not used, the libasyncProfiler.so …
=> #955 Add an asprof option to specify the path of libasyncProfier.so in the container

src/converter/one/jfr/JfrClass.java, src/converter/one/jfr/JfrField.java
Make JfrClass `field()` method public so that event classes are able to read the fields found within the respective event and make parsing decisions based on found fields.
The Jfr event G1HeapSummary introduced the field `oldGenUsedSize` which only exists for jdk21. This change allows parsers to check for this dynamic field by calling the `field()` method in the `JfrClass`.
Built locally.
---
=> Make JfrClass field() public for field visibility in Jfr Event classes.

src/flightRecorder.cpp, src/frameName.cpp, src/frameName.h, src/vmEntry.h
This is a partial fix for https://github.com/async-profiler/async-profiler/issues/974, complementing JDK-8268364.
Backported JDK-8268364 into Java 17 and tested with reproducer at [gist](https://gist.github.com/krk/a0800bac5bc5a01709be85637285a965):
```
javac Main.java
gcc -shared -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" -fPIC repro.cpp -orepro.so
java -agentpath:"$(pwd)/repro.so" -Xmx100m Main
```
=> Avoid JVM crash by deleting JNI refs after calling GetMethodDeclaringClass

test/one/profiler/test/TestProcess.java, test/test/kernel/KernelTests.java
Fix the timeout of the `KernelTests#notLinux` test by not running it with `/usr/bin/sudo`.
Running `/usr/bin/sudo` on Mac as a non-root user, asks the user for a password infinitely, so the running the profiler with sudo causes timeouts on Mac. 
Ran it on Mac with different Java versions.
---
=> Fix KernelTests#notLinux test

.gitignore, src/log.cpp, src/log.h, src/profiler.cpp, src/writer.cpp, src/writer.h
"Profiling started" and other messages are now INFO loglevel and will respect the current loglevel.
https://github.com/async-profiler/async-profiler/issues/960
All messages should respect loglevel, "Profiling started" etc. messages did not.
With different `loglevel` parameters:
```
java ... -agentpath: ...,loglevel=info ...
Profiling started
```
```
java ... -agentpath: ...,loglevel=warn ...
```
---
=> Profiling output respects loglevel.

Makefile
I am trying to cross-compile async-profiler binaries in my CI. I am doing this on x86_64 host. Unfortunately, `ARCH_TAG` is getting rewritten by the unconditional `uname -a`. Additionally, current build produces the binaries that claim they are `3.0`, but that is misleading.
No related issues?
Enough configuration to make cross-compiled builds work.
The default invocation of `make clean release` seems to produce the same result. For cross-compilation testing, I added this patch into my build pipeline, and then set `PROFILER_VERSION=nightly ARCH_TAG=... CROSS_COMPILE=...`. It produces the following binaries: https://builds.shipilev.net/async-profiler/
---
[Apache 2.0 …
=> Make profiler version and arch tag configurable

test/test/lock/LockTests.java, test/test/recovery/RecoveryTests.java, test/test/smoke/LoadLibrary.java
Running RecoveryTests and LoadLibrary sometimes fail on the macos github action runner by a small margin. Lowering the passing threshold by a bit helps them pass more reliably.
The LockTests are also broken, so also disabling them temporarily
While implementing nightly builds using github actions, these tests have been flaky, sometimes just missing the threshold for passing the test.
This has been tested by them running on the macos github actions runner successfully
---
=> Tweak tests so that they pass more reliably

src/objectSampler.cpp, src/objectSampler.h, src/profiler.cpp, src/vmEntry.cpp, src/vmEntry.h, test/one/profiler/test/TestProcess.java, test/test/alloc/AllocTests.java
Only one JVM TI agent can hold can_generate_sampled_object_alloc_events capability at a time. To avoid multiple profiler instances from conflicting with each other, profiler should obtain the capability only when needed and release it as soon as a profiling session finishes.
This allows multiple different async profiler instances to use the object sampler on the same java process one after the other. 
Verifying that the test fails without implementation changes: https://github.com/openorclose/async-profiler/actions/runs/11050192717/job/30697437468#step:6:51
---
=> Obtain can_generate_sampled_object_alloc_events JVMTI capability only when needed

src/converter/Main.java, src/converter/one/convert/Arguments.java, src/converter/one/convert/JfrConverter.java, src/converter/one/jfr/event/EventAggregator.java
Add jfrconv `--grain` option to coarsen flame graphs by subsamling stack traces.
Shape of the result flame graph should be similar to the original one.
Example:
```
jfrconv --grain 4 source.jfr dest.html
```
will produce a flame graph that is 4 times smaller in number of samples.
Grain value can be fractional. E.g., to shrink a flame graph containing 314 samples to 100 samples, specify `--grain 3.14`
There are two main use cases for the feature:
1. Reduce flame graph size by dropping out least relevant stacks.
2. Normalize flame graphs so that they contain a fixed number of samples.
---
=> An option to coarsen flame graphs

test/one/profiler/test/Runner.java
While running `make test`, print test args and inputs from annotations if present.
Test logs for each test should be unique:
```
INFO: Running XTests.abc
INFO: Running XTests.abc
INFO: Running XTests.abc
```
vs.
```
INFO: Running XTests.abc inputs: [0]...
INFO: Running XTests.abc inputs: [10000]...
INFO: Running XTests.abc inputs: [1000000]...
```
`make test`
---
=> Log test args and inputs.

.github/workflows/nightly.yml
Point to the correct codebuild runners meant for this async-profiler repository
https://github.com/async-profiler/async-profiler/pull/998
These were still pointing to the codebuild runners for a different forked repository
---
=> Update paths to codebuild runners

.github/workflows/nightly.yml
Refactor nightly builds to delete previous release and create a new release with new binaries
The current implementation always uploads nightly builds to the same nightly release. This nightly release is tagged to a particular commit and remains unchanged, causing confusion to users. Furthermore, the source code files can't be modified for a release, so only the binaries get updated, causing a mismatch between source code and binaries
Example workflow run: 
https://github.com/openorclose/async-profiler/actions/runs/11404731913
---
=> Refactor nightly builds to delete previous release and create a new release

src/flightRecorder.cpp, src/frameName.cpp
`jmethod_class` *may* not be initialized in all code paths.
```
make test
```
---
=> Fix possible uninitialized variable access, method_class.

src/dwarf.cpp
`rem_*` variables *may* not be initialized in all code paths.
```
make test
```
---
=> Initialize rem_* in DwarfParser.parseInstructions.

src/main/main.cpp
Buffer smaller than `PATH_MAX` would cause silent truncation when path length is larger than the buffer size.
To eliminate possible silent filename truncation, which may cause an error or surprising behavior.
```
make test
asprof start and check libpath value.
```
---
=> Increase setup_lib_path buf size to PATH_MAX

.github/workflows/test-and-publish-nightly.yml
Upload hs_err logs to artifacts
This helps us debug failing tests in github actions such as https://github.com/async-profiler/async-profiler/actions/runs/11729589309/job/32675573581?pr=1036
created a hs_err.log file directly during testing. will remove after github actions for PR is executed
Example run containing a hs_err log: https://github.com/async-profiler/async-profiler/actions/runs/11743903048?pr=1050
---
=> Upload hs_err logs to artifacts

src/symbols_linux.cpp
Prevents an unlikely uninitialized access.
```
make test
```
---
=> Initialize CodeCache to NULL.

test/test/lock/LockTests.java
Modified `LockTests.datagramSocketLock` to check the sum of `ReentrantLock.lock()` and `ReentrantLock.unlock()`
The test assumes `ReentrantLock.lock()` takes > 10%, but sometimes, it is `ReentrantLock.unlock()` the one that takes time. This may cause the test to sometimes fail.
```
make TESTS=test.lock.LockTests test
```
Test passes, although this is not a guarantee as problem is not consistent
```
Total test duration: 15.311 s
Results Summary:
PASS: 4 (100.0%)
FAIL: 0
SKIP (disabled): 0
SKIP (config mismatch): 0
TOTAL: 4
```
---
=> Fix errors in LockTests.datagramSocketLock

.github/workflows/test-and-publish-nightly.yml
Run tests on multiple Corretto versions.
Tests in the CI use Corretto 11. Run tests on Corretto 17, 21 and 23 as well, for the linux x64 target.
`make test` in CI.
---
=> Test corretto 11, 17, 21, 23 in CI.

README.md
Update build status badge in README.md to new workflow
There is a new workflow now and the old ci.yml has been deleted, leading to a broken badge. 
This changes the README to use the correct one at https://github.com/async-profiler/async-profiler/actions/workflows/test-and-publish-nightly.yml/badge.svg?branch=master
Test out the change right here
```
Build status: [![Build Status](https://github.com/async-profiler/async-profiler/actions/workflows/test-and-publish-nightly.yml/badge.svg?branch=master)](https://github.com/async-profiler/async-profiler/actions/workflows/test-and-publish-nightly.yml)
```
Build status: [![Build Status](https://github.com/async-profiler/async-profiler/actions/workflows/test-and-publish-nightly.yml/badge.svg?branch=master)](https://github.com/async-profiler/async- …
=> Update build status badge in README.md to new workflow

docs/FlamegraphInterpretation.md
Color coding image for flamegraph positioning is not correct.
---
=> Rectify flamegraph colors guide positioning.

docs/FlamegraphInterpretation.md, docs/ProfilingNonJavaApplications.md
Fix misses and build issues in Non Java profiling example in documentation.
N/A
N/A
Compiled with `gcc NonJava.c -o NonJava -I/home/roysouma/workplace/async-profiler/src -L/home/roysouma/workplace/async-profiler/build/lib -lasyncProfiler -ldl -Wl,-rpath=/home/roysouma/workplace/async-profiler/build/lib` and program ran as expected.
---
=> Fix misses and build issues in Non Java profiling example in documentation.

src/cpuEngine.cpp, src/cpuEngine.h, src/ctimer_linux.cpp, src/itimer.cpp, src/os.h, src/os_linux.cpp, src/os_macos.cpp, src/perfEvents_linux.cpp, test/one/profiler/test/Output.java, test/test/cpu/CpuBurner.java, test/test/cpu/CpuTests.java, test/test/jfr/JfrTests.java
Leverage `si_overrun` for scaling total CPU time counted in `ctimer` mode.
Sampling frequency in ctimer mode depends on the kernel `CONFIG_HZ` configuration, which is typically 250 or 100 Hz. This means, profiling intervals should be multiple of 4ms/10ms, or they will not work as expected.
Fortunately, if profiling interval is set to a smaller value, Linux will pass the number of missed samples (number of times the timer would have triggered) in `si_overrun` field of `siginfo`. We can use this value to compute actual CPU time.
Usual tests + new `ctimerTotal` and `itimerTotal` unit tests.
---
=> Count missed samples when estimating total CPU time in ctimer mode

test/native/testRunner.hpp
In addition to const char*, accept char* as string as well.
Assertions should compare `char*` values as strings, in addition to `const char*` values.
`make test-cpp`
---
=> Fix CHECK_OP string assertions.

Makefile
I noticed that my own cross-compiled binaries from https://builds.shipilev.net/async-profiler/ do not build cleanly anymore. In fact, there is a bug in `Makefile`, introduced by this hunk:
https://github.com/async-profiler/async-profiler/commit/3cf733d58970f8c130b659821e244150eef40ee8#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R19
The problem is that `CC` and `CXX` are pre-defined in GNU Make: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html. So, `?=` does not work well: it _never_ overwrites to `$(CROSS_COMPILE)...`, which results in binaries being compiled by host compiler, and only later `strip` discovers the binary format is wrong:
```
$ ARCH_TAG=aarch64 CROSS_COMPILE=/home/buildbot/deps/x-tools/aarch64-linux-gnu/bin/aarch64-linux-gnu …
```
=> Regression: Cross-compilation does not work after CC/CXX changes

src/arch.h, src/callTraceStorage.cpp, src/profiler.cpp, src/vmEntry.h
Add an explicit padding field on 64-bit platforms and fill it with zero when converting from JVMTI to AGCT frames.
https://github.com/async-profiler/async-profiler/discussions/1089
Implement the 3rd option in the discussion above.
Manual tested.
Byte 4 to 7 is changed to zero when calculating the hash for lock sample. see bellow
```
#0  CallTraceStorage::calcHash (this=0x7fff70021308, num_frames=646, frames=0x7fff707f95a0) at src/callTraceStorage.cpp:177
#1  0x00007fffcc39235e in CallTraceStorage::put (this=0x7fff70021308, num_frames=646, frames=0x7fff707f95a0, counter=77567752) at src/callTraceStorage.cpp:231
#2  0x00007fffcc3adb56 in Profiler::recordSample (this=0x7fff700191f0, ucontext=0x0, counter=77567752, event_type=LOCK_SAMPLE, event=0x7fffcc9321f0) at src/profiler.cpp:709
#3 …
```
=> fix stack trace memory pollution #1089

src/res/heatmap.html
Reduce max canvas size
https://github.com/async-profiler/async-profiler/issues/418
My tests with chrome shows that if canvas dimensions become greater than 16384x16384 pixels on any side, any draw operations became significantly slower, so let's fix it with 16384.
Locally with latest chrome version.
---
=> Reduce max canvas size

src/res/heatmap.html
Iterative flamegraph rendering causes races with user actions. This commit takes user actions into account during rendering.
Just clicked here and there) Maybe more testing required.
---
=> Click on flamegraph while it is in progress mess

Makefile
https://github.com/async-profiler/async-profiler/pull/1082
Allow setting `CC`, `CXX`, `STRIP` from env vars without breaking the `CROSS_COMPILE` sugar.
```
make
CC=gcc14-gcc CXX=gcc14-c++ make
CC= CXX= make CROSS_COMPILE=x86_64-redhat-linux-
```
---
=> Keep CC/CXX env changes without breaking CROSS_COMPILE

test/one/profiler/test/TestProcess.java, test/test/alloc/AllocTests.java, test/test/jfr/JfrTests.java, test/test/nativemem/NativememTests.java
1. Test LD_PRELOAD mechanism to start async-profiler.
2. Test JFR-to-collapsed conversion of non-Java profiles.
PR includes additional refactoring:
- `%lib` can be used as a placeholder for the path to `libasyncProfiler.so`;
- `TestProcess.getFilePath()` as a shortcut for `TestProcess.getFilePath().getAbsolutePath()`.
Basic coverage of non-Java profiling.
Also, a regression test for 3d950aed897fd58e1b4fea82b2f833750f49d3b4.
---
=> LD_PRELOAD nativemem test

test/native/testRunner.hpp
`reinterpret_cast<const char*>(nullptr)` does not compile
---
=> Fixed compilation failure with gcc12

src/flightRecorder.cpp
Before this PR, the clock setting in the JFR contains which clock we attempted to use. This changes it to contain the actual clock used, so if there was a failed attempt to use the tsc clock, it will say "monotonic".
Tested locally to do the right thing
=> jfr: set the clock setting to the actual rather than attempted clock

src/flightRecorder.cpp, src/lockTracer.cpp, src/tsc.cpp, src/tsc.h
Supports clock=tsc without a JVM. See #1106.
The clock calibration logic has been copied from https://github.com/metrics-rs/quanta
unit tests + tested locally
---
=> support clock=tsc without a JVM

src/tsc.h
This PR makes tsc mode work on aarch64 using cntvct_el0. As far as I can tell, e.g. from [the quanta crate](https://github.com/metrics-rs/quanta/blob/e185d38e56e2743368c92c812d479e2f04dc168d/src/detection.rs), the cntvct timestamp is invariant on all aarch64 machines.
It's supposedly not available on iOS but then AFAICT async-profiler doesn't run on iOS either.
Fixes #1139
jfrs with a tsc allow for easier alignment between traces from the application and samples. aarch64 (ARM 64-bit) architecture is getting more and more popular, and it's useful to allow tsc-based profiling on aarch64 as well.
Tested manually on a Graviton 2 machine.
---
[Apache 2.0 license]: …
=> support tsc mode on aarch64 using cntvct_el0

.github/workflows/test-and-publish-nightly.yml
After the latest commit merge, the "publish" step fails for nightly build. Ref: https://github.com/async-profiler/async-profiler/pull/1154#issuecomment-2692474105 
Root cause: While downloading artifacts in the workflow, we filter the test files via `*.*` regex. In the above PR, the name of the test artifacts uploaded contained `24.04` in the string (since it uses display.runson and we are forced to use `24.04` there). Thus, these test logs were not getting filtered and as a result, the Javascript which only expected files, also started seeing directories (of test artifacts) and thus the failure. 
This PR uses `runson.display` instead of `runson.name` to circumvent the issue.
https://github.com/async-profiler/async-profiler/pull/1154#issuecomment-2692474105
In the PR #1154 we moved to GH …
=> CI/CD: use runson.display for publishing test artifacts instead of runson.name

test/test/lock/RaceToLock.java
After migrating to GH Runners for CI, we started seeing that the `raceToLocks` test in `LockTests` class started failing intermittently. The test fails because sometimes the wait time for threads with "shared lock" is lesser than that of threads using "random lock" - the thread randomly chooses one lock from the two available locks. To stabilize this, instead of using two locks, we use three. See below on how was this tested.
N/A
Available locks: 2
Test run count: 10
Total failures: 2
Total success: 8
PR: https://github.com/visheshruparelia/async-profiler/pull/4 (See diff)
Builds: https://github.com/visheshruparelia/async-profiler/actions/runs/13686306015 (Notice that Attempt 6 and Attempt 8 failed - attached screenshot)
Available locks: 3
Test run count: 10
Total failures: 0
Total …
=> LockTests - use 3 locks for random threads instead of 2 to improve UT stability

src/converter/one/jfr/Dictionary.java, src/converter/one/jfr/JfrReader.java
The commit includes the following changes:
* Adding a size method for the custom Dictionary implemetnation.
https://github.com/async-profiler/async-profiler/issues/1170
Ability to easily retrieve unique stacktraces in a profiled jfr output
Tested with a crash reproducer generating a jfr output and using JfrReader to get the unique stacktraces count.
---
=> Add functionality to get unique stacktraces count from JFR output

src/os_linux.cpp, src/symbols_linux.cpp
```bash
$ make MERGE=false
mkdir -p build/bin
mkdir -p build/lib
g++  -O3 -fno-exceptions -fno-omit-frame-pointer -fvisibility=hidden -std=c++11  -U_FORTIFY_SOURCE -Wl,-z,defs -Wl,--exclude-libs,ALL -static-libstdc++ -static-libgcc -fdata-sections -ffunction-sections -Wl,--gc-sections -momit-leaf-frame-pointer -DPROFILER_VERSION=\"3.0\" -I/usr/lib/jvm/java-21-openjdk-amd64/include -Isrc/helper -I/usr/lib/jvm/java-21-openjdk-amd64/include/linux -fPIC -shared -o build/lib/libasyncProfiler.so src/allocTracer.cpp src/arguments.cpp src/asprof.cpp src/callTraceStorage.cpp src/chk.cpp src/codeCache.cpp src/cpuEngine.cpp src/ctimer_linux.cpp src/demangle.cpp src/dictionary.cpp src/dwarf.cpp src/engine.cpp src/fdtransferClient_linux.cpp src/flameGraph.cpp src/flightRecorder.cpp src/frameName.cpp …
```
=> Fix compilation with source merging disabled

.github/workflows/test-and-publish-nightly.yml
Test with the latest corretto release 24, instead of 23.
Keep LTS releases + latest major.
`make test`
---
=> test with Corretto 24 instead of 23, now that it is out

test/test/lock/LockTests.java
This PR removes the comparison between waiting time for shared and random locks in `RaceToLock`.
#1199
The removed check is not always successful, and this does not depend on Async-Profiler.
---
=> Remove waiting time comparison in `LockTests#raceToLocks`

test/test/lock/LockTests.java, test/test/lock/RaceToLock.java
In this PR, I amend the test `LockTests#raceToLocks` to add a new check to assert that threads locking with strong contention are sampled more frequently than threads locking with light contention. 
The idea is that `semiShared` threads always lock an uncontended (thread-local) lock except for a minority of the cases, i.e. once every `SHARED_LOCK_INTERVAL`. `shared` threads always lock on the contended lock.
#1199 
The test needs to be fixed to make sure profiling locks works properly.
`make test` both locally and in CI.
---
=> Amend `LockTests#raceToLocks` to test profiling results of contended locks

Makefile
Sort sources to zInit is last, ensuring its statics are initialized last - this works in gcc versions after 4.7.0 (related https://gcc.gnu.org/bugzilla/show_bug.cgi?id=46770).
https://github.com/async-profiler/async-profiler/issues/1214
```
make MERGE=false
```
and starting the profiler with any target, as in https://github.com/async-profiler/async-profiler/issues/1214.
---
=> Always sort sources so zInit is last.

src/callTraceStorage.cpp, src/callTraceStorage.h
Ignore raw call trace id when it is greater than total capacity of table in callTraceStorage.
https://github.com/async-profiler/async-profiler/issues/1206
Prevent a crash during wall clock profiling in the rarest of rare case of delayed signal delivery used by asprof.
Working on a reproducer to reliably crash and always reliably test. At this point, this is a non breaking logical change to just return and not add call trace id in case it is greater than the total capacity of the hashtable in callTraceStorage
---
=> Ignore raw call trace id when it is greater than total capacity of table in callTraceStorage.

src/asprof.cpp, src/asprof.h, src/event.h, src/flightRecorder.cpp, src/jfrMetadata.cpp, src/jfrMetadata.h, src/userEvents.cpp, src/userEvents.h
This adds an (unstable) `profiler.UserEvent` JFR event, that can be emitted by user native code and contain custom data.
Using T_STRING for the data instead of T_BYTE/F_ARRAY due to a bug in `jfr print`:
```
java.lang.NullPointerException
at jdk.jfr/jdk.jfr.internal.tool.PrettyWriter.printValue(PrettyWriter.java:357)
at jdk.jfr/jdk.jfr.internal.tool.PrettyWriter.printArray(PrettyWriter.java:281)
at jdk.jfr/jdk.jfr.internal.tool.PrettyWriter.printValue(PrettyWriter.java:325)
at jdk.jfr/jdk.jfr.internal.tool.PrettyWriter.printFieldValue(PrettyWriter.java:273)
at jdk.jfr/jdk.jfr.internal.tool.PrettyWriter.print(PrettyWriter.java:213)
at jdk.jfr/jdk.jfr.internal.tool.PrettyWriter.print(PrettyWriter.java:76)
at jdk.jfr/jdk.jfr.internal.tool.EventPrintWriter.print(EventPrintWriter.java:79)
at …
```
=> add support for user JFR events

Makefile, src/mallocTracer.cpp, src/symbols_linux.cpp
Fixing several issues which I encountered while working on #1226:
- https://github.com/async-profiler/async-profiler/pull/1226#issuecomment-2797294532
- `malloc` is not properly hooked sometimes, thus native memory profiling does not work properly. The problem is not malloc-specific, other similar functions are affected as well
#1136 
We want to fully support Alpine and other musl-based environment.
`docker run --privileged -it --rm -v $(pwd):/async-profiler amazoncorretto:11-alpine-jdk sh -c 'apk add --no-cache musl-dev util-linux make gcc g++ linux-headers && cd /async-profiler && rm -rf build && make -j test'`
---
[Apache 2.0 license]: …
=> Fix musl-specific problems

src/mallocTracer.cpp
In this PR I change the enforced optimizaton level to `O0` for dummy hooks.
#1235 
Clang does not support `O1`. https://reviews.llvm.org/D126984
---
=> Skip compiler optimizations for dummy malloc hooks

Makefile, src/symbols_linux.cpp, test/native/libs/callsmalloc.c, test/one/profiler/test/RunnableTest.java, test/one/profiler/test/Test.java, test/test/nativemem/NativememTests.java, test/test/nativemem/profile_with_dlopen.c
Parse symbols and hook functions of the main executable, when profiler is *not* loaded via `LD_PRELOAD`.
Without this fix, profiler is unable to hook non-java executables if `dlopen` is called after starting the profiler. 
Issue was introduced in https://github.com/async-profiler/async-profiler/pull/1220 as `dlerror` may *not* return `NULL` for the main executable.
Thanks for the repro in https://github.com/async-profiler/async-profiler/issues/1241 @Baraa-Hasheesh  and for discussions @fandreuz and @Baraa-Hasheesh.
Fixes https://github.com/async-profiler/async-profiler/issues/1233 and https://github.com/async-profiler/async-profiler/issues/1241.
`make test-java TESTS=nativemem`
---
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 …
=> Add nativemem test with dlopen after profiler start.

src/symbols_linux.cpp
Use `AT_BASE` from `auxv` to get loader base address and parse it regardless of dlopen/dlerror results.
https://github.com/async-profiler/async-profiler/issues/1250
The loader itself cannot be unloaded, so what dlopen/dlerror returns is not relevant. This simplifies and corrects the condition of calling `parseProgramHeaders`.
`make test`
---
=> Detect and parse the loader in parseLibraries.

.github/workflows/test-and-publish-nightly.yml, Makefile
In this PR I split the GHA job `build-binaries-and-test` in two jobs:
- `build-and-upload-binaries`: build release, run unit tests, upload artifacts
- `integration-tests`: run integration tests
<details>
</details>
I changed a bit how we publish publication:
- Removed the confusing `.tar.gz` and `.zip` in the *artifact name* (not *artifact path*, which stays the same), since anyway GHA would create an archive named `{artifact_name}.zip`, thus resulting in a file named `{artifact_name}.zip.zip` or `{artifact_name}.tar.gz.zip`
- The tree stays the same though
- *Question*: do we really need to publish a `.tar.gz`/`.zip` here? We could simply upload the artifact as a directory, and GHA will take care of zipping it, this would also simplify the workflow in this PR 
- JAR artifacts are now …
=> Separate jobs for build/unit tests and integration tests

.github/workflows/test-and-publish-nightly.yml
Artifacts are [not properly discovered](https://github.com/async-profiler/async-profiler/actions/runs/14667937072/job/41167591394) due to a change in the naming pattern.
#1253 broke it
We should fix nightly publication
https://github.com/fandreuz/async-profiler/actions/runs/14668389291/job/41168859417
---
=> Fix nightly publication

test/test/cpu/CpuTests.java
The stdout pollutes test logs in GHA.
n/a
Before:
<details>
<code>
INFO: Running CpuTests.itimerTotal...
INFO: Running CpuTests.perfEventsTargetCpuEventsCount...
PASS [20/75] CpuTests.itimerTotal took 2.797 s
pid 758's current affinity list: 0-3
pid 758's new affinity list: 0
pid 759's current affinity list: 0-3
pid 759's new affinity list: 0
pid 760's current affinity list: 0-3
pid 760's new affinity list: 0
pid 761's current affinity list: 0-3
pid 761's new affinity list: 0
pid 762's current affinity list: 0-3
pid 762's new affinity list: 0
pid 763's current affinity list: 0-3
pid 763's new affinity list: 0
pid 764's current affinity list: 0-3
pid 764's new affinity list: 0
pid 765's current affinity list: 0-3
pid 765's new affinity list: 0
pid 766's current affinity list: 0-3
pid 766's …
=> Redirect only stderr from `taskset` in integration tests

src/os_linux.cpp, src/profiler.cpp
If `OS::replaceCrashHandler()` is called before JVM start, it may setup signal handler without `SA_SIGINFO` flag, causing `segvHandler` to work incorrectly.
---
=> Make sure siginfo is passed to custom SEGV handler

src/fdtransfer.h, src/fdtransferClient.h, src/fdtransferClient_linux.cpp, src/main/fdtransferServer_linux.cpp, src/perfEvents_linux.cpp, test/test/kernel/KernelTests.java
Extend fdtransfer protocol to pass probe name in perf_event requests.
Async-profiler can profile kprobes and uprobes, e.g. `asprof -e kprobe:fd_install`. However, this does not work with `--fdtransfer` option. The reason is, `perf_event_attr` structure contains a pointer to kprobe/uprobe name, but when `perf_event_attr` is passed to another process (fdtransfer server), this pointer becomes invalid, since the address belongs to a different process.
The proposed solution extends `perf_fd_request` structure with a new field that contains a name of kprobe/uprobe. For events other than kprobe/uprobe, this field contains an empty string. When fdtransfer server receives non-empty probe name, it adjusts pointer in `perf_event_attr`.
Added `KernelTests.kprobe` test, which failed before the fix, …
=> Allow profiling kprobes/uprobes with --fdtransfer

test/test/comptask/ComptaskTests.java
I noticed some sporadic failures of the new `comptask` test (#1293) on JDK8.
The reason for this failure is that sometimes `C2Compiler::compile_method;java/lang/Thread.<init>` is not found in the stacktrace. I had a look at the code, and noticed that `Thread.<init>` was relatively simple in JDK8, while some complexity was delegated to [`Thread.init`](https://github.com/openjdk/jdk8/blob/master/jdk/src/share/classes/java/lang/Thread.java#L363). Indeed, I get this from `-XX:+PrintCompilation`:
```
278  106    b  3       java.lang.Thread::<init> (49 bytes)
278  107    b  4       java.lang.Thread::<init> (49 bytes)
279  106       3       java.lang.Thread::<init> (49 bytes)   made not entrant
279  108    b  3       java.lang.Thread::init (214 bytes)
280  109    b  4 …
```
=> Fix `comptask` test flakyness on JDK8

docs/ConverterUsage.md, docs/ProfilingModes.md, src/converter/Main.java, src/converter/one/convert/Arguments.java, src/converter/one/convert/JfrConverter.java, src/converter/one/jfr/event/MallocLeakAggregator.java
For native leak profiling, ignore allocations made in the last 10% of the profiling session.
#1064 introduced the feature to create a flamegraph of native memory allocations. With `--leak` option, only those allocations are displayed that do not have matching `free` calls - such allocations are considered memory leaks. However, this algorithm is biased towards allocations made closer to the end of the profiling session, because such allocations are more likely to be freed only after the session has ended.
To avoid such a bias, it is proposed to simply ignore younger allocations. For example, if a profiling session runs for 10 minutes, allocations made during the last minute won't be included in the leak flamegraph.
Created an artificial memory leak by not closing `DirectoryStream` and ran …
=> Skip last 10% allocations for leak detection

src/symbols_linux.cpp
It's possible for the profiler to try to parse more libs than it's specified limit which may result in an out of bounds exceptions 
This was discovered while writing dlopen heavy applications that load thousands of shared objects
N/A
Prevent the profiler from crashing & exceeding it's limits 
the dlopen heavy application is no longer crashing 
---
=> Prevent parsing more libs than the MAX_NATIVE_LIBS limit

Makefile, test/native/libs/reladyn.c, test/native/symbolsTest.cpp
As mentioned in description, Enabling more tests to run on Mac that were previously disabled
N/A
Enable as much of the available tests to run on all platforms
`make test`
---
=> Enable unit tests related to parsing for MacOs

src/profiler.cpp, src/safeAccess.h, src/vmStructs.cpp, src/vmStructs.h
The problem happens when a sample lands in HotSpot's `Thread::~Thread()` in a short window between
```
if (osthread() != nullptr) os::free_thread(osthread());
```
and
```
if (this == Thread::current_or_null()) {
Thread::clear_thread_current();
}
```
and freed `osthread` memory is concurrently reused by some other thread.
#1319
Fix confirmed by the original bug reporter.
New stress test is underway.
---
=> #1319: Accessing osThreadId of a terminating thread may fail

src/flightRecorder.cpp, src/index.h, src/jfrMetadata.cpp, src/jfrMetadata.h, src/profiler.cpp
We can clean up `jfrMetadata.cpp` a bit by using `index.h`.
GHA
---
=> Use `Index` in `jfrMetadata`

test/test/stackwalker/StackwalkerTests.java
Change the assertions on Stackwalker tests to be more restrictive to avoid false negatives
The check now explicitly checks for main with native stack frame from the JNI call which shouldn't exist due to unwinding checks 
N/A
reduce random failures on GHA
`make test`
---
=> Change stackwalker test checks to be more restrictive

.github/workflows/code-check.yml, .github/workflows/linters.yml, .github/workflows/test-and-publish-nightly.yml
In this PR I introduce some changes to cancel in-progress GHA runs when they are superseded by a new run:
```yaml
concurrency:
group: ${{ github.workflow }}-${{ github.ref }}
cancel-in-progress: true
```
This advices the workflow orchestrator to cancel any previous run of group `${{ github.workflow }}-${{ github.ref }}`. Variable references [here](https://docs.github.com/en/actions/reference/contexts-reference#github-context), more info in [GHA docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow).
n/a
Keeping redundant runs is generally not useful: 
- it does not provide useful information for the developer, since the most recent run is what we're interested in
- it clutters the GitHub …
=> Cancel redundant in-progress GHA runs

test/one/profiler/test/TestProcess.java
keep all logs for debugging purposes 
This fix the following problems:
* If multiple profiling sessions are done, each session will overwrite the previous one logs 
* If a test depends on both profiler session logs & process logs only one of those logs will be kept
* Not all generated profiler logs were saved
N/A
Make debugging flakey tests easier
`make test`
---
=> Save all generated logs for debug purposes

Makefile
`build/test.jar` has a dependency on `test/deps`, because the JAR should be rebuilt when a new dependency JAR is pulled in. In this PR I add an invocation to `mkdir` at the beginning of the Makefile to make sure that the directory exists.
@Baraa-Hasheesh experienced the problem in his local environment. We did not spot that during GHA runs because we pull in dependencies there (Protobuf Java runtime). 
The recipe should not fail if the directory does not exist.
Tested locally.
---
=> Create `test/deps` if it does not exist before running Makefile recipes

.github/workflows/code-check.yml
In this PR I remove the step responsible for creating review comments based on the output from clang-tidy. I'll leave the step which runs clang-tidy so developers can still look at its output.
I'll revert this change when I find a solution to have a token which can get `pull-requests:write` permissions. Our organization configuration only grants read access.
n/a
In the current state, the step will fail with HTTP 403 whenever the action tries to create a comment.
n/a
---
=> Temporarily disable clang-tidy automatic comments

src/os.h, src/os_linux.cpp, src/os_macos.cpp, src/zInit.cpp, test/one/profiler/test/TestProcess.java, test/test/c/CTests.java
Add proper checking to validate that the profiler was preloaded as to avoid false starts
Currently if `ASPROF_COMMAND` env variable is defined any dlopen on the profiler will cause it to start which means the profiler might start with incorrect profiling options
Furthermore in this case async-profiler will assume that preload hooks exists which might not be true, which will to incomplete profiling by the profiler
N/A
Avoid false early starts for the async-profiler
New test added
`make test`
---
=> Correctly check if profiler is preloaded

.github/workflows/test-and-publish-nightly.yml, src/instrument.cpp
From the looks of it for certain compilers an implicit casting was causing wrong logical & mathematical operations 
This in turn caused bad byte modification by the profiler for the Java class 
#1380
Fix bug in instrument profiling
GHA added for macOs JDK 17 which was causing the issue to happen consistently 
---
=> fix crashes when using instrument profiling

src/stackWalker.cpp
In Alpine, we have seen cases where unwinding does not terminate properly (only terminates after we reach maxDepth value). This results in flamegraphs with a lot of "duplicate" frames. This happens because during unwinding, the next "pc" is always equal to current "pc" after a certain point. 
In this PR, we add a check where we terminate the unwinding if `prev_sp == new_sp and prev_pc == new_pc`.
N/A
Attached are before and after images of flame graphs for CPU profiling for [this application](https://github.com/async-profiler/async-profiler/blob/master/test/test/lock/DatagramTest.java) in Alpine
---
=> improve terminate logic in dwarf and vm stack walking mode

src/arch.h, src/profiler.cpp, src/stackWalker.cpp
VMStructs-based stack walker could crash on ARM64 for allocation or nativemem events.
#1389 
The crash was caused by the combination of two issues:
1. gcc 13.3 changed frame prologue on AArch64. Previously, frame base `x29` was always pointing to `sp`, but now it is no longer the case. E.g.:
```
2ba10:       d107c3ff        sub     sp, sp, #0x1f0
...
2ba20:       a91a7bfd        stp     x29, x30, [sp, #416]
2ba24:       910683fd        add     x29, sp, #0x1a0
```
Therefore, the value returned by `callerSP()` was incorrect. Since there is no simple way to get caller SP, we will start stack walking from the current frame rather than a caller frame on ARM64.
2. Because of the above error, stack unwinding code attempted to access signal context when it should not. `alloc` and `nativemem` …
=> #1389: Incorrect top frame for synchronous events with cstack=vm on ARM64

.clang-tidy
These checks proved to be too harsh.
n/a
https://github.com/async-profiler/async-profiler/pull/1411#discussion_r2236703796
https://github.com/async-profiler/async-profiler/pull/1411#discussion_r2236704079
n/a
---
=> Remove some clang-tidy checks

src/otlp.h, src/profiler.cpp, src/profiler.h, test/one/profiler/test/TestProcess.java, test/test/otlp/OtlpTemporalityTest.java, test/test/otlp/OtlpTests.java
Implemented proper temporal aggregation support where consecutive dumps maintain the same time_nanos (session start) but show increasing duration_nanos, while profiler restarts generate new time_nanos values. Converted _start_time to nanosecond precision.
Not available
This change ensures proper temporal data interpretation across profiler sessions by providing precise timing information that allows OTLP consumers to distinguish between different profiling periods.
Added a new test
---
=> Add time_nanos and duration_nanos to OTLP profiles with test

test/test/otlp/OtlpTests.java
The recently introduced test `OtlpTests.otlpAggregationTemporalityTest` spawns a child process. If a `NoClassDefFoundError` happens in the child, it's harder to detect for the test runner.
#1413
The expected behavior is to see the test listed in the `SKIP (missing JAR)` category.
Instead, we got this:
```
INFO: Running OtlpTests.otlpAggregationTemporalityTest...
Error: Unable to initialize main class test.otlp.OtlpTemporalityTest
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/MessageOrBuilder
FAIL [1/1] OtlpTests.otlpAggregationTemporalityTest took 0.748 s
java.lang.AssertionError
at test.otlp.OtlpTests.otlpAggregationTemporalityTest(OtlpTests.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at …
```
=> Proactively check classpath in tests spawning a child process

.github/workflows/test-and-publish-nightly.yml
In this PR I disable `fail-fast` error handling strategy in GHA matrix runs. This means all matrix entries will run until completion of integration tests, instead of being cancelled as soon as one fails.
Docs [here](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#handling-failures).
n/a
I felt some frustration about GHA cancelling all tests as soon as one of the matrix entries fails. Sometimes I just want to see all errors.
https://github.com/fandreuz/async-profiler/actions/runs/15065133649/job/42348221865
---
=> [GHA] Disable matrix fail-fast

test/test/jfr/JfrMultiModeProfiling.java, test/test/jfr/JfrTests.java
Modify the parseMultiModeRecording for better reliability 
There are 2 problems:
* getWaitedTime isn't not 100% accurate => Make the check more relaxed
public long getWaitedTime()
Returns the **approximate accumulated elapsed time** (in milliseconds) that the thread associated with this ThreadInfo has waited for notification since thread contention monitoring is enabled. I.e. the total accumulated time the thread has been in the [WAITING](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.State.html#WAITING) or [TIMED_WAITING](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.State.html#TIMED_WAITING) state since thread contention monitoring is enabled. This method returns -1 if thread contention monitoring is disabled.
* Not all samples are captured due to sampling …
=> Update parseMultiModeRecording for better checks

src/flightRecorder.cpp, src/index.h
In this PR I fix the incompatibility between newly written JFR files, and the previous version of Async-Profiler's JFR reader.
Incompatibility introduced in #1378.
JFR produced by Async-Profiler should be backward compatible.
Manual testing.
---
=> Preserve compatibility with old JFR reader

src/instrument.cpp, test/test/instrument/CpuBurner.java, test/test/instrument/InstrumentTests.java
In this PR I introduce support for simple `*` wildcards (both for class and method) in the event selector for the `Instrument` engine. This is now valid:
- `event=*.*`
- `event=*.<init>`
- `event=java.lang.Thread.*`
#1421
This feature is mainly aimed at testing extensively #1421. Instrumenting all methods in a run loading a considerable amount of classes will give us confidence about the changes.
`make test-java -j TESTS=instrument`
---
=> Allow wildcards in `Instrument` profiling engine

src/protobuf.cpp, test/native/protobufBufferTest.cpp
Fix bug in ProtoBuffer::field(protobuf_index_t index, const char* s, size_t len) where the function was using strlen(s) instead of the provided len parameter, causing it to write more data than intended.
N/A
Discovered while debugging an OTLP test failure in the context of signal correlation. This could lead to buffer overruns and incorrect protobuf serialization when the caller wants to write only a portion of a string.
Added unit test.
---
=> Fix sized string writer method in protobuf writer

src/profiler.cpp, src/profiler.h
It seems that the field `Profile:: _symbol_map` is unused, let me know if I missed something.
n/a
If unused, we can remove it. Not really a big difference though, just 4kb in memory:
Before:
```
Call trace storage:   10244 KB
Flight recording:       0 KB
Dictionaries:      72 KB
Code cache:    9942 KB
------------------------------
Total:   20258 KB
```
After:
```
Call trace storage:   10244 KB
Flight recording:       0 KB
Dictionaries:      68 KB
Code cache:    9942 KB
------------------------------
Total:   20254 KB
```
GHA
---
=> `Profile:: _symbol_map` is unused

src/dwarf.cpp, src/dwarf.h, src/stackWalker.cpp, test/native/libs/jninativestacks.c, test/test/stackwalker/StackGenerator.java, test/test/stackwalker/StackwalkerTests.java
For the following FDE in DWARF, if a sample was captured between instructions at locations **0x2f544** & **0x2f55c**,
The profiler will use the following FrameDesc `loc = 0x2f544, cfa_reg = 0x1f, cfa_off = 32, fp_off = 0x80000000, pc_off = 0`
In this case the DWARF denotes the RA as invalid for these instructions so we should use the `lr` register ,
However the encoded FrameDesc would result in reading the return address from the `sp` rather than using `lr`
That results in reading random values, which results in `unknown` frame or just fail to unwind
```
000045f8 0000000000000024 000045fc FDE cie=00000000 pc=000000000002f540..000000000002f870
LOC           CFA      x29   ra    
000000000002f540 sp+0     u     u     
000000000002f544 sp+32    u     u     
000000000002f55c sp+32    c-16 …
```
=> Encode a default invalid RA for ARM FrameDesc 

.github/workflows/build.yml, .github/workflows/integ.yml, .github/workflows/test-and-publish-nightly.yml
Before this PR, all integration tests depended on all builds, causing e.g. linux-x64 integration tests to wait for macos build.
This is now fixed with some cosmetic changes to make the UI look like attached:
Integration tests should not wait for builds on unrelated OS/archs.
By the current PR github action.
---
=> Fix integration test dependencies to build and cosmetic changes

test/test/kernel/KernelTests.java
It was observed that when running async-profiler tests on some Alpine ARM instances that some of the integration tests can fail being:
* KernelTests.fdtransfer
* KernelTests.kernel
When checking the logs I noticed the following samples 
```
test/kernel/ListFiles.main;test/kernel/ListFiles.listFiles;java/io/File.list;java/io/File.normalizedList;java/io/UnixFileSystem.list;Java_java_io_UnixFileSystem_list;readdir_r;readdir;__sys_trace_return_[k];SyS_getdents64_[k];iterate_dir_[k];touch_atime_[k];__atime_needs_update_[k];current_time_[k];current_kernel_time64_[k] 4
```
The test checks if `sys_getdents` exists, but in this case the function is actually reported as `SyS_getdents`, which causes a failure
Comparing for either should be fine as in some Older Linux kernels we can see
```
#define …
```
=> Fix failing KernelTests
