async-profiler/async-profiler

src/perfEvent.cpp
src/spinLock.h
src/stackFrame.cpp

Recreated request to remove redundant commits. 
OK, I've updated the files. Now I limite a number of supported CPU by ARMv7 and higher due to DMB and YIELD instructions need. Verified on RPI2, build check only for x86

Support linux-arm platfrom. ARMv7 and higher only

---

src/jattach.c

* macOS support for temporary directory discovery
* Container support by entering mount namespace and considering
pid namespace differences between container and host

Update jattach with changes from upstream

---

src/arguments.cpp
src/arguments.h
src/jattach.c
src/perfEvents.h
src/perfEvents_linux.cpp
src/profiler.cpp
src/profiler.h

Add support for different perf events:
* HW cycles
* branch-misses
* context-switches
* LLC/L1D load misses
* cache-misses

Perf events support

---

CHANGELOG.md
Makefile
README.md
profiler.sh
src/allocTracer.cpp
src/allocTracer.h
src/arguments.cpp
src/arguments.h
src/engine.h
src/frameName.cpp
src/javaApi.cpp
src/lockTracer.cpp
src/lockTracer.h
src/perfEvents.h
src/perfEvents_linux.cpp
src/perfEvents_macos.cpp
src/profiler.cpp
src/profiler.h
src/vmEntry.cpp
src/vmEntry.h
src/vmStructs.cpp
src/vmStructs.h
test/alloc-smoke-test.sh

- The infrastructure for profiling HW and SW perf counters
- Kernel tracepoints support
- Lock profiling (contented `monitorenter` events)

Perf events and Lock profiling

---

README.md
profiler.sh
src/jattach/jattach.c

jattach will automatically change current user/group to match target process owner

Allow profiling any Java process when run under root

---

profiler.sh

this should work on all target platforms

improve profiler.sh for work with symlink

---

README.md

Extended troubleshooting section for https://github.com/jvm-profiling-tools/async-profiler/issues/193

Added additional case for Troubleshooting section

---

src/vmStructs.cpp
src/vmStructs.h

_length was changed to _length_and_refcount

Add Java 12 memory profiling support

---

README.md
src/arch.h
src/instrument.cpp
src/instrument.h
src/os.h
src/os_linux.cpp
src/os_macos.cpp
src/profiler.cpp
src/vmEntry.cpp
src/vmEntry.h

Profile invocations of an arbitrary Java method, i.e. record all stack traces, where the methods is called.

Java method instrumentation

---

Makefile
NOTICE

According to http://www.apache.org/legal/resolved.html#category-b,
it's not enough to have this on the file header.

Add NOTICE with CDDL license header

---

profiler.sh

This way, it works for containers as well.
Only case where it doesn't work is when `/tmp` is an absolute symlink (therefore `/proc/pid/root/tmp` will point to e.g `/tmp2` which is not available in the host). If `/tmp` is an absolute symlink and we're profiling a host process, it will, of course, work just fine (so we're not regressing it here).
Tested it manually by profiling a container with `-e cpu`. Without this change, `profiler.sh` exits with no output. With this change, I get the expected `[WARN] perf_event_open failed: Operation not permitted` lines.

Read log file via /proc/pid/root

---

.travis.yml

Ref: https://docs.travis-ci.com/user/reference/bionic

Travis CI: use Ubuntu 18.04 (Bionic Beaver)

---

Makefile
src/arch.h
src/stackFrame_ppc64.cpp

Hi Andrei,
as discussed, here is the new pull request. I include `<signal.h>` in stackFrame_ppc64.cpp now. On SuSE it works, of course, but I wasn't able to check this on ubuntu. 
Have a nice WE,
Gunter

port async profiler 2.0 to Power Linux little endian (linuxppc64le), step 2

---

README.md

Some readme update at the method profiling section

---

pom.xml

Fixes java version to be compatible with try-with-resources (already used in several source files).
It helps IDE to recognize language level correctly.

Bump java plugin source/target version

---

src/converter/Main.java

Prevents users like me wasting time

Converter: add warning when running with -jar instead of -cp

---

src/symbols_linux.cpp

Parse symbols from debuginfod cache as a fallback. Cache can be found at `$DEBUGINFOD_CACHE_PATH`, `$XDG_CACHE_HOME/debuginfod_client/` or `$HOME/.cache/debuginfod_client/`, whichever folder is found first.
https://github.com/async-profiler/async-profiler/issues/929
To simplify use cases when debuginfod is easier to use.
Tested with the Dockerfile and sample java app that loads libcrypt and does SHA-512 hashing to keep CPU busy in the native-land: https://gist.github.com/krk/6df8ccd561bfa76a1a7e236e42baad1c
Without symbols loaded:
```
ns  percent  samples  top
----------  -------  -------  ---
5270020407   94.58%      527  /usr/lib/libcrypt.so.2.0.0
39999796    0.72%        4  /usr/lib/libc.so.6
```
with `debuginfod-find debuginfo /lib64/libcrypt.so`:
```
ns  percent  samples  top …
```

#929 Load symbols from debuginfod cache

---

test/one/profiler/test/Output.java
test/one/profiler/test/TestProcess.java
test/test/cpu/Cache.java
test/test/cpu/CpuTests.java

The commit includes the following changes:
* Add JFR to Collapsed conversion implementation.
* Enable disabled JFR tests.
N/A
Enable previously disabled JFR test with necessary corrections
Tested on AL2_x86_64, AL2_aarch64 and M1 MacOs Sonoma
---

Enable jfr tests

---

src/arguments.cpp
src/arguments.h
src/flightRecorder.cpp
src/frameName.cpp
src/main/main.cpp
src/profiler.cpp
src/vmEntry.h

An option to display instruction addresses

---

test/test/jfr/JfrMutliModeProfiling.java

Add a copyright header for a file missed in PR#1005
N/A
N/A
Cosmetic change. No specific testing required.
---

Add missing copyright header.

---

docs/OutputFormats.md

Fix JfrVisualization URL

---

README.md

I think "how to build" sounds more natural.
none
fix possible typo
none
---

fix possible typo

---

src/converter/one/convert/FlameGraph.java

#1182: Retain by-thread grouping when reversing FlameGraph

---

Makefile
test/native/libs/vaddrdif.c
test/native/libs/vaddrdif.ld
test/native/symbolsLinuxTest.cpp

Add test for https://github.com/async-profiler/async-profiler/issues/1176
`make test-cpp`
---

Add test for having different offset and virtaddr for LOAD segment

---

.github/workflows/test-and-publish-nightly.yml

Description
Fixes https://github.com/async-profiler/async-profiler/issues/1208
Related issues
https://github.com/async-profiler/async-profiler/issues/1208
Motivation and context
See related issue
How has this been tested?
GHA
---

Run tests on MacOS with X64 JDK

---

test/test/jfr/JfrMultiModeProfiling.java
test/test/jfr/JfrTests.java

In this PR I fix a mistyped file name used in `JfrTests`.
n/a
Fixing a typo.
GHA
---

Fix typo in `JfrTests`

---

src/profiler.cpp

This PR applies a change already discussed in #1336, to simplify the code that handles writing the location table for OTLP dumps.
---

Simplify location handling in OTLP

---

test/test/alloc/AllocTests.java
test/test/jfr/JfrTests.java
test/test/nativemem/NativememTests.java

Give tests unique suffix to make debugging failures on GHA easier
This will cause each test to generate a unique log file that's not overridden by follow up tests
N/A
make debugging flaky tests on GHA easier
make test
---

Give tests unique suffix names

---

src/otlp.h
src/profiler.cpp
test/one/profiler/test/Output.java
test/test/otlp/CpuBurner.java
test/test/otlp/OtlpTests.java

`thread.name` is an optional `Sample` attribute. We can provide it when it is available.
#1436
Will simplify testing of #1436.
New test.
---

Thread name in OpenTelemetry output
